// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgfdzqmhzrgsqiujjacf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZmR6cW1oenJnc3FpdWpqYWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzI4MzAsImV4cCI6MjA2NTY0ODgzMH0.NunSC-vHH84Dr5EbQtmylAsiYpodWUoHEwlDealHS0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);